<<<<<<< HEAD
# Generated by Django 4.2 on 2024-10-26 18:11
=======
# Generated by Django 4.2 on 2024-10-26 17:04
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
