# Generated by Django 4.2 on 2024-10-26 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da consulta')),
                ('allergies', models.TextField(max_length=400, verbose_name='Alergias')),
                ('issues', models.TextField(max_length=400, verbose_name='Problemas recorrentes')),
                ('medication', models.TextField(max_length=400, verbose_name='Medicação')),
                ('anamnesis', models.TextField(max_length=500, verbose_name='Anamnese')),
                ('new_medication', models.TextField(max_length=400, verbose_name='Nova medicação')),
                ('exams', models.TextField(max_length=400, verbose_name='Exames')),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='patient.consult', verbose_name='Consulta')),
                ('medic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='médicos', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
    ]
